//------------------------------------------------------------------------------
// <auto-generated>
// Hello
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Net.Sendvia.Models
{
	///<summary>
	///Parcel dimension information.
	///</summary>
	public partial class Dimension
	{
		///<summary>
		///Parcel height in millimeters
		///</summary>
		public virtual int Height
		{get;set;}
	
		///<summary>
		///Parcel length in millimeters
		///</summary>
		public virtual int Length
		{get;set;}
	
		///<summary>
		///Parcel width in millimeters
		///</summary>
		public virtual int Width
		{get;set;}
	
	}
}