//------------------------------------------------------------------------------
// <auto-generated>
// Hello
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Net.Sendvia.Models
{
	///<summary>
	///
	///</summary>
	public partial class GuidArray
	{
		///<summary>
		///
		///</summary>
		public virtual List<Guid> Ids
		{get;set;}
	
	}
}