//------------------------------------------------------------------------------
// <auto-generated>
// Hello
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Net.Sendvia.Models
{
	///<summary>
	///
	///</summary>
	public partial class Pdf
	{
		///<summary>
		///
		///</summary>
		public virtual byte[] Data
		{get;set;}
	
	}
}