//------------------------------------------------------------------------------
// <auto-generated>
// Hello
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Net.Sendvia.Models
{
	public partial class Setting
	{
		public virtual string Key
		{get;set;}
	
		public virtual string Value
		{get;set;}
	
		public virtual string RegEx
		{get;set;}
	
	}
}